name: go_dart_ffi
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Vyacheslav Egorov <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  ffi: any

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
